/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2018-11-22 23:39:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta name=\"veiwport\" content=\"width=device-width\" , initial-scale=\"1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.css\">\r\n");
      out.write("<title>맛나맛나</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("#header {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        /*전체 폼 div태그*/\r\n");
      out.write("\r\n");
      out.write("        #form {\r\n");
      out.write("            margin-right: auto;\r\n");
      out.write("            margin-left: auto;\r\n");
      out.write("            width: 500px;\r\n");
      out.write("            float: center;\r\n");
      out.write("            background-color: #ffffff\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        #header img {\r\n");
      out.write("            margin: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("         #randomNumber {\r\n");
      out.write("            font-size: 37px;\r\n");
      out.write("            font-style: italic;\r\n");
      out.write("            text-align: right;\r\n");
      out.write("            margin: 0px 70px;\r\n");
      out.write("            margin-left: 110px;\r\n");
      out.write("            height: 30px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /*로그인 버튼*/\r\n");
      out.write("\r\n");
      out.write("        .button {\r\n");
      out.write("            width: 350px;\r\n");
      out.write("            height: 55px;\r\n");
      out.write("            border: 0px;\r\n");
      out.write("            margin-top:30px;\r\n");
      out.write("            outline: 0px;\r\n");
      out.write("            background: #ff7348;\r\n");
      out.write("            color: rgb(255, 255, 255);\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: 0.3s;\r\n");
      out.write("            font-family: sans-serif;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .button:hover {\r\n");
      out.write("            background-color: #ff8d6b;\r\n");
      out.write("            color: rgb(77, 77, 77);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("       <div class=\"col-lg-4\"></div>\r\n");
      out.write("       <div class=\"col-lg-4\">\r\n");
      out.write("          <div style=\"padding-top: 20px;\">\r\n");
      out.write("          \r\n");
      out.write("          <div id=\"header\">\r\n");
      out.write("            <img src=\"images/logo/main_logo.png\" width=\"280px\" />\r\n");
      out.write("        </div>\r\n");
      out.write("             <form method=\"post\" action=\"loginAction.jsp\">\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                  <input type=\"text\" class=\"form-control\" placeholder=\"아이디\" name=\"userID\" maxlength=\"20\">\r\n");
      out.write("                 </div>\r\n");
      out.write("                 <div class=\"form-group\">\r\n");
      out.write("                  <input type=\"password\" class=\"form-control\" placeholder=\"비밀번호\" name=\"userPassword\" maxlength=\"20\">\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                 <div id=\"randomNumberDiv\"> \r\n");
      out.write("                    <p style=\"text-align:center;\">보이는대로 입력해주세요</p>\r\n");
      out.write("                    <span id=\"randomNumber\"></span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <span class=\"formBox\">\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"randomNumberInput\" size=30/>\r\n");
      out.write("                </span>\r\n");
      out.write("                <div>\r\n");
      out.write("                 <input type=\"submit\" id=\"login_ok\" class=\"button\" value=\"로그인\">\r\n");
      out.write("                 </div>\r\n");
      out.write("             </form>\r\n");
      out.write("             </div>\r\n");
      out.write("          </div>\r\n");
      out.write("       <div class=\"col-lg-4\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"js/bootstrap.min.js\"></script> \r\n");
      out.write("<script>\r\n");
      out.write("            window.onload = function () {\r\n");
      out.write("                var getRandomNumberId = document.getElementById(\"randomNumber\");\r\n");
      out.write("                var randomNumber = Math.floor(Math.random() * 1000000 + 1);\r\n");
      out.write("    \r\n");
      out.write("                getRandomNumberId.innerHTML = randomNumber;\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("                var getLoginButtonId = document.getElementById(\"login_ok\");\r\n");
      out.write("    \r\n");
      out.write("                getLoginButtonId.onclick = function () {\r\n");
      out.write("                    LoginEvent();\r\n");
      out.write("                }\r\n");
      out.write("    \r\n");
      out.write("                var LoginEvent = function () {\r\n");
      out.write("                    var getRandomNumberInputId = document.getElementById(\"randomNumberInput\");\r\n");
      out.write("                    var getUserNumberValue = getRandomNumberInputId.value; //받은 숫자 값을 변수에 넣음\r\n");
      out.write("                    var getLoginFormId = document.getElementById(\"login_ok\");\r\n");
      out.write("    \r\n");
      out.write("                    if (randomNumber == getUserNumberValue) { //받은 숫자와 랜덤 넘버 비교\r\n");
      out.write("                        getLoginFormId.submit();\r\n");
      out.write("                    } else {\r\n");
      out.write("                        alert(\"입력한 숫자가 다릅니다.\");\r\n");
      out.write("                        getLoginFormId.reset();\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
