/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2018-11-23 01:56:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.PrintWriter;
import bbs.Bbs;
import bbs.BbsDAO;

public final class view_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.io.PrintWriter");
    _jspx_imports_classes.add("bbs.Bbs");
    _jspx_imports_classes.add("bbs.BbsDAO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta name=\"veiwport\" content=\"width=device-width\" , initial-scale=\"1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.css\">\r\n");
      out.write("\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Montserrat:900\" rel=\"stylesheet\">\r\n");
      out.write("<title>맛나맛나</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("#navbar {\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            background-color: rgb(216, 83, 6);\r\n");
      out.write("            font-family: 'Montserrat', sans-serif;\r\n");
      out.write("            position: sticky;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            z-index: 1;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #navbar a {\r\n");
      out.write("            float: left;\r\n");
      out.write("            display: block;\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            padding: 35px 50px;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-size: 17px;\r\n");
      out.write("            transition-property: background-color, color;\r\n");
      out.write("            transition-duration: 0.5s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #navbar a:hover {\r\n");
      out.write("            color: rgba(0, 0, 0, 0.7);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .content {\r\n");
      out.write("            padding: 16px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .sticky {\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .sticky+.content {\r\n");
      out.write("            padding-top: 60px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .button {\r\n");
      out.write("            width: 350px;\r\n");
      out.write("            height: 55px;\r\n");
      out.write("            border: 0px;\r\n");
      out.write("            margin-top:30px;\r\n");
      out.write("            outline: 0px;\r\n");
      out.write("            background: #ff7348;\r\n");
      out.write("            color: rgb(255, 255, 255);\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: 0.3s;\r\n");
      out.write("            font-family: sans-serif;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .button:hover {\r\n");
      out.write("            background-color: #ff8d6b;\r\n");
      out.write("            color: rgb(77, 77, 77);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    ");

        String userID = null;
        if (session.getAttribute("userID") != null ) {
        	userID = (String)session.getAttribute("userID");
        }
        int bbsID=0;
        if(request.getParameter("bbsID") != null) {
        	bbsID = Integer.parseInt(request.getParameter("bbsID"));
        }
        if(bbsID==0) {
        	   PrintWriter script =response.getWriter();
        	   script.println("<script>");
        	   script.println("alert('유효하지 않은 글입니다')");
        	   script.println("location.href='bbs.jsp'");
        	   script.println("</script>");
        }
        Bbs bbs = new BbsDAO().getBbs(bbsID);
    
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <!-- Navigation-->\r\n");
      out.write("    <div id=\"navbar\">\r\n");
      out.write("        <a href=\"main.jsp\">HOME</a>\r\n");
      out.write("        <a id=\"news\" href=\"#chart\">TOP25</a>\r\n");
      out.write("        <a href=\"#boardTitle_list\">BOARD</a>\r\n");
      out.write("        <a href=\"#about\">ABOUT</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("        <div class=\"row\" style=\"text-align:center;margin-top:30px;\">\r\n");
      out.write("        \r\n");
      out.write("           <table class=\"table table-striped\" style=\"text-align: center; border: 0px soild #dddddd\">\r\n");
      out.write("                \r\n");
      out.write("                <tbody>\r\n");
      out.write("                     <tr>\r\n");
      out.write("                          <td style=\"font-size:15px;width: 7%;height:70px;vertical-align:middle\">글 제목</td>\r\n");
      out.write("                          <td style=\"font-size:15px;width: 47%;vertical-align:middle\" colspan=\"2\">");
      out.print(bbs.getBbsTitle().replaceAll(" ", "&nbsp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll("\n", "<br>"));
      out.write("</td>\r\n");
      out.write("                          <td style=\"font-size:15px;width: 7%;vertical-align:middle;\">작성자</td>\r\n");
      out.write("                         <td style=\"font-size:15px;width: 10%;vertical-align:middle; colspan=\"2\">");
      out.print(bbs.getUserID() );
      out.write("</td>\r\n");
      out.write("                         <td style=\"font-size:15px;width: 9%;vertical-align:middle\">작성일자</td>\r\n");
      out.write("                         <td style=\"font-size:15px;width: 20%;vertical-align:middle; colspan=\"2\">");
      out.print( bbs.getBbsDate().substring(0, 11) + bbs.getBbsDate().substring(11, 13) + "시" + bbs.getBbsDate().substring(14, 16) + "분" );
      out.write("</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td colspan=\"2\" style=\"min-height: 200px; text-align: left;font-size:20px\">");
      out.print( bbs.getBbsContent().replaceAll(" ", "&nbsp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll("\n", "<br>"));
      out.write("</td>\r\n");
      out.write("                                                \r\n");
      out.write("                     </tr>\r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("            <a href=\"bbs.jsp\" class=\"btn btn-primary\">목록</a>\r\n");
      out.write("              ");

                 if(userID != null && userID.equals(bbs.getUserID())) {
              
      out.write("\r\n");
      out.write("                      <a href=\"update.jsp?bbsID=");
      out.print(bbsID);
      out.write("\" class=\"btn btn-primary\">수정</a>\r\n");
      out.write("                      <a onclick=\"return confirm('정말로 삭제하시겠습니까?')\" href=\"deleteAction.jsp?bbsID=");
      out.print(bbsID);
      out.write("\" class=\"btn btn-primary\">삭제</a>\r\n");
      out.write("              ");

                 }
              
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"js/bootstrap.min.js\"></script> \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
