/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2018-11-23 00:51:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.PrintWriter;

public final class write_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.io.PrintWriter");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta name=\"veiwport\" content=\"width=device-width\" , initial-scale=\"1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.css\">\r\n");
      out.write("<style>\r\n");
      out.write("/*Navigation*/\r\n");
      out.write("\r\n");
      out.write("        #navbar {\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            background-color: rgb(216, 83, 6);\r\n");
      out.write("            font-family: 'Montserrat', sans-serif;\r\n");
      out.write("            position: sticky;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            z-index: 1;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #navbar a {\r\n");
      out.write("            float: left;\r\n");
      out.write("            display: block;\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            padding: 35px 50px;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-size: 17px;\r\n");
      out.write("            transition-property: background-color, color;\r\n");
      out.write("            transition-duration: 0.5s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #navbar a:hover {\r\n");
      out.write("            color: rgba(0, 0, 0, 0.7);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #navbar a.active {\r\n");
      out.write("            background-color: rgb(231, 231, 231);\r\n");
      out.write("            color: rgb(0, 0, 0);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #navbar a.active:hover {\r\n");
      out.write("            background-color: rgb(231, 231, 231);\r\n");
      out.write("            color: rgb(216, 83, 6);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .content {\r\n");
      out.write("            padding: 16px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        .sticky+.content {\r\n");
      out.write("            padding-top: 60px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        #board_write_title {\r\n");
      out.write("            font-family: 'Gugi', cursive;\r\n");
      out.write("            background-color: rgba(255, 255, 255, 0);\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-top: 50px;\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("        }\r\n");
      out.write("        .button {\r\n");
      out.write("            width: 350px;\r\n");
      out.write("            height: 55px;\r\n");
      out.write("            border: 0px;\r\n");
      out.write("            margin-top:30px;\r\n");
      out.write("            outline: 0px;\r\n");
      out.write("            background: #ff7348;\r\n");
      out.write("            color: rgb(255, 255, 255);\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: 0.3s;\r\n");
      out.write("            font-family: sans-serif;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            float: right;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .button:hover {\r\n");
      out.write("            background-color: #ff8d6b;\r\n");
      out.write("            color: rgb(77, 77, 77);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>맛나맛나</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    ");


int pageNumber = 1;

if (request.getParameter("pageNumber") != null){

	pageNumber = Integer.parseInt(request.getParameter("pageNumber"));

}

String userID = null;
               if(userID == null) {
           
      out.write("\r\n");
      out.write("                      <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("         <li class=\"dropdown\">\r\n");
      out.write("           <a href=\"#\" class=\"dropdown-toggle\" \r\n");
      out.write("            data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\" \r\n");
      out.write("            aria-expanded=\"false\">접속하기 <span class=\"caret\"></span></a>\r\n");
      out.write("        <ul class=\"dropdown-menu\">\r\n");
      out.write("              <li><a href=\"login.jsp\">로그인</a></li>\r\n");
      out.write("              <li><a href=\"join.jsp\">회원가입</a></li>\r\n");
      out.write("            </ul>    \r\n");
      out.write("         </li>\r\n");
      out.write("       </ul>\r\n");
      out.write("           ");

               } else {
           
      out.write("\t   \r\n");
      out.write("                          <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("         <li class=\"dropdown\">\r\n");
      out.write("           <a href=\"#\" class=\"dropdown-toggle\" \r\n");
      out.write("            data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\" \r\n");
      out.write("            aria-expanded=\"false\">회원관리<span class=\"caret\"></span></a>\r\n");
      out.write("        <ul class=\"dropdown-menu\">\r\n");
      out.write("              <li><a href=\"logoutAction.jsp\">로그아웃</a></li>\r\n");
      out.write("            </ul>    \r\n");
      out.write("         </li>\r\n");
      out.write("       </ul>\r\n");
      out.write("           ");

               }
           
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- header -->\r\n");
      out.write("    ");

        
        if (session.getAttribute("userID") != null ) {
        	userID = (String)session.getAttribute("userID");
        }
    
      out.write("\r\n");
      out.write("        <!-- Navigation-->\r\n");
      out.write("    <div id=\"navbar\">\r\n");
      out.write("        <a href=\"main.jsp\">HOME</a>\r\n");
      out.write("        <a id=\"news\" href=\"#chart\">TOP15</a>\r\n");
      out.write("        <a href=\"#boardTitle_list\">BOARD</a>\r\n");
      out.write("        <a href=\"#about\">ABOUT</a>\r\n");
      out.write("    </div>\r\n");
      out.write("           \r\n");
      out.write("       </div>\r\n");
      out.write("    </nay>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("        <div colspan=\"2\" id=\"board_write_title\" ><img src=\"images/logo/write.png\" width=\"300px\"></div>\r\n");
      out.write("          <form method=\"post\" action=\"writeAction.jsp\">\r\n");
      out.write("           <table = class=\"table \" style=\"text-align: center; border: 0px soild #dddddd\">\r\n");
      out.write("                \r\n");
      out.write("                <tbody>\r\n");
      out.write("                     <tr>\r\n");
      out.write("                          <td><input type=\"text\" class=\"form-control\" placehoder=\"글 제목\" name=\"bbsTitle\" maxlength=\"50\"></td>\r\n");
      out.write("                     </tr>\r\n");
      out.write("                     <tr>\r\n");
      out.write("                          <td><textarea class=\"form-control\" placehoder=\"글 내용\" name=\"bbsContent\" maxlength=\"2048\" style=\"height: 350px\";></textarea></td>\r\n");
      out.write("                     </tr>\r\n");
      out.write("\r\n");
      out.write("                </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("           <div style=\"width:100%\"><input type=\"submit\" class=\"button\" value=\"글쓰기\"></div>\r\n");
      out.write("          </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- \r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"js/bootstrap.min.js\"></script> \r\n");
      out.write("-->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
